### ISSUE TITLE
Poly1305 is not suitable for key derivation

### ISSUE THREAD

**Issue by samuel-lucas6** [covert-encryption/aehash#1]
As specified in [section 2.7](https://datatracker.ietf.org/doc/html/rfc8439#section-2.7) of [RFC 8439](https://datatracker.ietf.org/doc/html/rfc8439), Poly1305 produces a biased output, meaning it shouldn't be used for key derivation. Therefore, I would argue using the authentication tag as part of the key is a bad idea. A better approach would be to use something like HMAC rather than an AEAD mode.

**Comment by covert-encryption** [comment]
@samuel-lucas6 Covert does not use Poly1305 for key derivation, only in combination with ChaCha20 for authentication, where it being biased should not matter as the underlying cipherstream is properly pseudorandom. If sufficiently biased, it could however affect the *indistinguishable from random* property, but I have not seen documentation of this being an issue in the way it is used in this AEAD (given that the ChaCha20 block0 used to initialise cannot be found without the proper key).

Perhaps I have overlooked something... Could you clarify?

**Comment by covert-encryption** [comment]
It is however used for signatures which are built on authentication being reliable. Perhaps you meant that? Indeed, the signature encryption key is derived with that, although that part of the spec is heavily subject to change. There is SHA-512 hashing in between each step, however, that should remove any bias.

**Comment by covert-encryption** [comment]
In case you saw my earlier response, now deleted, nevermind that - didn't notice that your comments were on AEhash, not Covert. AEhash is not memory-strong unless a large number of rounds are used and we intend no further development on this experiment, as fixing that issue would already require too much more complexity, likely removing any speed benefit over Argon2.

It needs to be noted that there is a new Wasm SIMD implementation of Argon2 that is already reasonably fast, and thus clearly preferred over this.

**Comment by covert-encryption** [comment]
Updated README.md to avoid confusion.

**Comment by samuel-lucas6** [comment]
I understand. I didn't intend on using it but thought it was an interesting idea. I played around with a similar design after seeing this but realised it wasn't going to work very well.

I was referring to the [ChaCha20-Poly1305 variant](https://github.com/covert-encryption/aehash/commit/b7385748dc43c0e78e4f13a2769dd5bcf62ef6be) you created. The round key is 16 bytes of ciphertext and the 16 byte tag, but Poly1305 shouldn't be used for key derivation, so it worsens half of the key.
